language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get -qq update
 - sudo apt-get -qq build-dep openafs
 - sudo apt-get install gfortran
script: ./bootstrap && ./configure --enable-tests && make -j8 && make -j16 check && make -j16 distcheck && sudo make install
